### PR TITLE
Fix edge cases on jsx-pascal-case

### LINKED ISSUE #1334: false negative with namespacing/qualifications using jsx-pascal-case
Using v7.1.0,
```jsx
<__this.MyComponent/>
<containerClass.MyComponent/>
<containerObject.MyComponent/>
```
flag an error (e.g Contained JSX component MyComponent must be in PascalCase (react/jsx-pascal-case))

### PR DESCRIPTION
**Pull request by yacinehmito**
Currently the rule `jsx-pascal-case` doesn't support some edge cases:
- It improperly errors when the component is in a namespace that starts with an underscore
- It improperly succeeds on the component is in camelCase
- It improperly succeeds in a bunch of cases where the component is in a namespace
- It doesn't accurately report the name of the component in some error cases

The PR should fix #1334

### CODE REVIEW

**Comment by yacinehmito** [comment]
There is no fix yet. I am waiting for #2636 to be merged.
For the moment the PR only adds new test cases.

**Comment by yacinehmito** [comment]
The PR #2638 is now sufficient to fix #1334.

Keeping this one around though to make sure we don't display an error when a colon is used in a tag.

**Comment by yacinehmito** [comment]
Fixed the test cases after having worked on #2638.
This showcases that #1334 is not truly fixed yet.

I'll work on it after #2636 and #2640 are sorted out.

**Comment by ljharb** [comment]
@yacinehmito are you interested in completing this PR?

**Comment by yacinehmito** [comment]
I am sorry, I lost interest as I was not using React anymore.

**Comment by yacinehmito** [comment]
It's been a year and a half. I am closing the PR because I want to clean up my Pull Request tab on GitHub. Feel free to open a new PR, or to reopen this one if someone shows up to finish it.

**Comment by ljharb** [comment]
It’s unfortunate that the pull requests tab encourages this behavior.

**Pull request closed without merging**
