### PR TITLE
WIP: react version detection in a monorepo

### PR DESCRIPTION
**Pull request by migueloller**
WIP pull request to track progress on #2218 .

### CODE REVIEW

**Comment by ljharb** [comment]
Seems like a good first start, but this would need tests.

Can you convert it to a draft PR, until it's ready?

**Comment by migueloller** [comment]
@ljharb, yup! I was just trying to see how involved this change was going to be. Because of the current test set up I'm probably going to have to spend some time figuring out the least invasive way to implement the tests.

I'll try to look into this again during the weekend.

**Comment by ljharb** [comment]
@migueloller any interest in completing this PR?

**Comment by migueloller** [comment]
@ljharb, in addition to the small tweak I did to the existing tests, were there specific test cases you were thinking we should cover?

**Comment by ljharb** [comment]
My hope would be, inside `tests/files`, a recreation of a monorepo setup where `detect` would have returned the wrong result without your change.

**Comment by migueloller** [comment]
@ljharb, got it. That sounds reasonable! I will do my best to get something set up sometime soon. I apologize I haven't put in more work on this PR, I've been busy 😬

**Comment by ljharb** [comment]
@migueloller are you no longer interested in this feature?

**Comment by ljharb** [comment]
The passage of time doesn't have any impact on relevance in open source :-)

My hope is that everybody using this plugin can use "detect", so if there are monorepo users unable to use it, then it's definitely worthwhile to fix it.

**Comment by migueloller** [comment]
Sounds good!

Thanks for the nudge 😄

**Comment by migueloller** [comment]
Well, as I was doing the rebase I noticed that `mater` now does consider `context` in the `detectReactVersion` function.

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/lib/util/version.js#L48-L72

Here's the PR that made the change: https://github.com/jsx-eslint/eslint-plugin-react/commit/eeb92731bd922af4493cf938f0547a021e5cdbcf

Seems like that's satisfactory?

**Comment by migueloller** [comment]
Ok, sorry for the delay in the response but I wanted to make sure I understood well how my changes and the current implementation in `master` differ before I could confirm it solves the problem. I just got around to that.

In my implementation I was using `context.getCwd` to determine the current working directory passed to the linter instance as documented [here](https://eslint.org/docs/latest/extend/custom-rules#the-context-object).

The current implementation is using `context.getFilename` instead, which seem like a better solution since it will find the relevant React version relative to the source file.

I did mention that using this API would be ideal: https://github.com/jsx-eslint/eslint-plugin-react/issues/2218#issuecomment-605589405. @jcrosetto ultimately got to it a year later: https://github.com/jsx-eslint/eslint-plugin-react/pull/2943

So, the project is indeed solved and I think we're good to close this.

Thanks again @ljharb and thanks @jcrosetto for taking the lead here and getting it fixed using `context.getFilename`.

**Pull request closed without merging**
