### PR TITLE
`no-unknown-property` add more `<video>` attributes, `onMouseMoveCapture ` and changes to rule documentation

### PR DESCRIPTION
**Pull request by sjarva**
This PR adds:
- `  autoPictureInPicture`, `controls`, `controlList`, `disablePictureInPicture`, `disableRemotePlayback`, `loop`, `muted`, `poster`,`preload` and allows them only on `<video>` element
- allows `<line>`, `<mask>` and `<use>` to have `fill` property
- allows `onError` property on `<link>` and `<source>` elements
- allows `onLoad` property on `<link>` element
- allows numbers in valid `data-*` properties
- moves `allowFullscreen` to case ignored properties
- unit tests for these properties
- adds a mention to `no-unknown-property` rule documentation about ignored properties, when using libraries that pass information with some new props (like `css` prop when using `emotion`)

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks!

Many of the video attrs also work on audio, so i added those too.

**Comment by ljharb** [comment]
Looks like it's `controlsList`, not `controlList`: #3397

**Comment by wereHamster** [comment]
How about `onLoad` on `iframe`? I've been successfully using this prop in the past, React handles it fine.

**Comment by ljharb** [comment]
@wereHamster see #3398.

**Pull request merged**
