### PR TITLE
autofix-unused-prop-type

### PR DESCRIPTION
**Pull request by Veveue**

### CODE REVIEW

**Comment by ljharb** [comment]
It seems very dangerous to me to assume that it's safe to remove just because it's unused. Autofixing has a very high bar for when it's safe, and "removal" is generally not done with autofixes.

**Comment by Veveue** [comment]
> It seems very dangerous to me to assume that it's safe to remove just because it's unused. Autofixing has a very high bar for when it's safe, and "removal" is generally not done with autofixes.

I want to automatically fix many unnecessary imports caused by copying and pasting code.

**Comment by ljharb** [comment]
Yes, but your desire to do less work doesn't mean the autofix is a safe thing to enable.

You could certainly implement this as a _suggestion_, though, if you like?

**Comment by Veveue** [comment]
I understand. I will handle this issue locally. Thank you for your suggestion!

**Pull request closed without merging**
