### PR TITLE
[Fix] `sort-prop-types`: Check for undefined before accessing `node.typeAnnotation.typeAnnotation`

### PR DESCRIPTION
**Pull request by tylerlaprade**
Fixes the bug reported in [this comment](https://github.com/jsx-eslint/eslint-plugin-react/issues/3763#issuecomment-2215163106)

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
We'll need a regression test before this fix can land.

**Comment by ljharb** [comment]
@tylerlaprade can you share the code that errored in your linked comment?

**Comment by tylerlaprade** [comment]
@ljharb, in a file with a `.tsx` extension, the following repros:

```typescriptreact
function Foo() {
  return <></>;
}
```

**Comment by ljharb** [comment]
@tylerlaprade hmm, can you confirm what version of the TS eslint parser you're using? it doesn't reproduce for me.

**Review by ljharb — APPROVED** [review]

**Comment by tylerlaprade** [comment]
Thanks for adding the test case! It looks like some snapshots need to be updated, but when I `npm test` locally, I don't see any failures.

**Comment by ljharb** [comment]
we don't use snapshots :-) it's just that some of the test jobs don't support fragments. i switched it to a div instead.

**Pull request merged**
