### PR TITLE
Clarify the number of examples.

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- clarifies these were three different examples.
- I didn't understand these were three different examples :)

### CODE REVIEW

**Comment by ljharb** [comment]
Typically it's better not to count the number, because then we have to update it every time we add or remove an example.

Perhaps instead, splitting it into separate code blocks?

**Comment by ioggstream** [comment]
> splitting it into separate code blocks?

That's ok! Can do it in this PR?

> Typically it's better not to count the number, 
> because then we have to update it every time we add or remove an example.

Yep. In some cases though, clarifying that is useful. E.g. see [this excerpt from the latest HTTP spec](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.10.2.3.p.6).

**Comment by ljharb** [comment]
Yes, let's split it in this PR instead of hardcoding a count.

**Review by ljharb — APPROVED** [review]
Thanks!

**Pull request merged**
