### PR TITLE
[Fix] `no-unknown-property`: add `fetchPriority`

### PR DESCRIPTION
**Pull request by SevereCloud**
See:

- [HTML Standard](https://html.spec.whatwg.org/multipage/indices.html#attributes-3:~:text=Sets%20the%20priority%20for%20fetches%20initiated%20by%20the%20element)
- [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchpriority)
- DefinitelyTyped/DefinitelyTyped#68645

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
added test coverage

**Comment by coreyward** [comment]
React is complaining about this:

Screenshot 2024-04-18 at 7 58 29 PM

**Comment by SevereCloud** [comment]
> React is complaining about this:
> 
> Screenshot 2024-04-18 at 7 58 29 PM

- https://github.com/facebook/react/pull/25927

PR has been merged, but not released

**Comment by ljharb** [comment]
ah, in that case we should detect the react version and only allow this property when react supports it. @SevereCloud can you file a new PR for that?

**Pull request merged**
