### PR TITLE
[Fix] `jsx-no-leaked-render`: invalid fixes in coerce mode

### LINKED ISSUE #3431: `jsx-no-leaked-render` performs redundant props check and invalid fix in coerce mode
# Context

There is a sample `Checkbox` component:

```typescript
const Checkbox = ({
  isChecked = false,
  isIndeterminate = false,
}: {
  isChecked?: boolean;
  isIndeterminate?: boolean;
}) => (
  <input 
    checked={isIndeterminate ? false : isChecked} 
    type="checkbox"
  />
);
```

The eslint config file contains a rule:

```
"react/jsx-no-leaked-render": ["error", { validStrategies: ["coerce"] }],
```

# Expected behavior

Linting the code raises no issues

# Actual behavior 

1. Eslint displays an error for the line:

```typescript
checked={isIndeterminate ? false : isChecked}
```

```
Potential leaked value that might cause unintentionally rendered values or rendering crasheseslint[react/jsx-no-leaked-render](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-no-leaked-render.md)
```

2. When auto-fix is performed, the code above is replaced with

```typescript
checked={!!isIndeterminate && false} 
```

which causes the logical issues (the `isChecked` is removed in that case).

### PR DESCRIPTION
**Pull request by akulsr0**
Fixes #3431

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks!

**Comment by ljharb** [comment]
@akulsr0 seems like tests are failing

**Comment by akulsr0** [comment]
@ljharb I am not sure why tests are failing here, I have tried with different node versions in local, its passing all test cases.

**Comment by ljharb** [comment]
The failures are in eslint < 5.

**Comment by ljharb** [comment]
I’m not sure why the output is different in eslint 3 and 4, but we may have to make the test output condition on eslint version.

**Comment by akulsr0** [comment]
Do we have any example case where output is based on eslint version?

**Comment by ljharb** [comment]
@akulsr0 mostly examples of test cases that are entirely skipped, but https://github.com/jsx-eslint/eslint-plugin-react/blob/12fe9447844ffed58c714c56bcfc89886a2ba5be/tests/lib/rules/sort-prop-types.js#L505-L540 should hopefully be enough for you to figure out how to adapt it?

**Comment by ljharb** [comment]
I tweaked your changes so the test cases still run in eslint 3, and it exposed a bug, which i then fixed. This should hopefully be good to go once tests pass.

**Pull request merged**
