### PR TITLE
feat: support eslint ^9

### PR DESCRIPTION
**Pull request by li-jia-nan**
feat: support eslint ^9

### CODE REVIEW

**Comment by Standard8** [comment]
I'm not a maintainer here, but this doesn't seem to be enough - see the comments on issue #3699

**Comment by li-jia-nan** [comment]
Sorry, I didn't notice that there was already an issue here, I closed this PR.

**Comment by Standard8** [comment]
Oh, sorry, I don't think you have to close it, but it does seem there's a bit more work than just bumping the compatible versions.

**Comment by ljharb** [comment]
I believe this was obsoleted by #3759.

**Pull request closed without merging**
